/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante;

import javax.swing.JOptionPane;

/**
 *
 * @author Janus
 */
public class JframeLogin extends javax.swing.JFrame {

    /**
     * Creates new form JframeLogin
     */
    public JframeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnIngresar = new javax.swing.JButton();
        BtnRegistrarse = new javax.swing.JButton();
        TxtUsuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        LbLogin = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();
        LbContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnIngresar.setBackground(new java.awt.Color(212, 175, 55));
        BtnIngresar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        BtnIngresar.setText("Ingresar.");
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BtnRegistrarse.setBackground(new java.awt.Color(212, 175, 55));
        BtnRegistrarse.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        BtnRegistrarse.setText("Registrarse.");
        jPanel1.add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 96, 30));
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, 30));

        LbLogin.setBackground(new java.awt.Color(51, 51, 255));
        LbLogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        LbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbLogin.setText("INICIO DE SESION");
        jPanel1.add(LbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 53));

        LbUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        LbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbUsuario.setText("USUARIO:");
        jPanel1.add(LbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 20));

        LbContraseña.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        LbContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbContraseña.setText("Contraseña:");
        jPanel1.add(LbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/User.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseClicked
String Username = "Administrador";
String Password = "1234";

String Pass = new String(Contraseña.getPassword());

if (TxtUsuario.getText().equals(Username) && Pass.equals(Password)) {
    System.out.println("Cambio para que se vea en git hub");
} else if (!TxtUsuario.getText().equals(Username)) {
    JOptionPane.showMessageDialog(this, "El usuario es incorrecto.");
} else if (!Pass.equals(Password)) {
    JOptionPane.showMessageDialog(this, "Contraseña Incorrecta");
} else {
    JOptionPane.showMessageDialog(this, "Usuario y contraseña son incorrectas.");
}   
    }//GEN-LAST:event_BtnIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel LbContraseña;
    private javax.swing.JLabel LbLogin;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
